version: "3"

services:

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.7
    restart: on-failure
    container_name: kafka
    ports:
      - "127.0.0.1:19092:19092"
    volumes:
      - panda-data:/var/lib/redpanda/data
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://kafka:9092,external://127.0.0.1:19092
      - --rpc-addr kafka:33145
      - --advertise-rpc-addr kafka:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=warn

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    container_name: redpanda-console
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - kafka
    volumes:
      - ./redpanda/console-config.yaml:/etc/redpanda-console/config.yaml:ro
    command: "/app/console"
    environment:
      CONFIG_FILEPATH: "/etc/redpanda-console/config.yaml"

volumes:
  panda-data: null
